base:
  branch: main
  dbt:
    commands:
    - python read_git_repo.py
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
target:
  dbt:
    commands:
    - python read_git_repo.py
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
