name: Run dbt + RipeRider manually

on:
  workflow_dispatch:
    inputs:
      git_repo_url:
        description: 'Git repo url to analyze'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up dbt + PipeRider
        run: |
          pip install -r requirements.txt
          pip install 'piperider[duckdb]'

      - name: Clone git repo ${{ github.event.inputs.git_repo_url }}
        run: |
          url=${{ github.event.inputs.git_repo_url }}
          git clone $url git_repo

      - name: Read git repo commits
        run: |
          python3 read_git_repo.py

      - name: Run dbt + PipeRider
        run: |
          dbt deps
          dbt run
          piperider run --dbt-state target/

      - name: Save reports
        run: |
          pushd .piperider/outputs/latest
          zip -r report.zip ./
          popd
          cp .piperider/outputs/latest/report.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: report-artifact
          path: report.zip
