name: Run dbt + RipeRider

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up dbt + PipeRider
        run: |
          pip install -r requirements.txt
          pip install 'piperider[duckdb]'

      - name: Clone git repo ${{ vars.GIT_REPO_URL }}
        run: |
          url=${{ vars.GIT_REPO_URL }}
          git clone $url git_repo

      - name: Read git repo commits
        run: |
          python3 read_git_repo.py

      - name: Run dbt + PipeRider for main branch
        run: |
          dbt run
          piperider run

      - name: Run dbt + PipeRider for current pull request
        run: |
          git fetch
          git checkout $GITHUB_HEAD_REF
          dbt run
          piperider run

      - name: Compare reports
        run: |
          piperider compare-reports --last

      - name: Save reports
        run: |
          mkdir -p artifact
          cp -r .piperider/outputs artifact/outputs
          cp -r .piperider/comparisons artifact/comparisons

      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: artifact/
