name: Run dbt + RipeRider

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up dbt + PipeRider
        run: |
          pip install -r requirements.txt
          pip install 'piperider[duckdb]'

      - name: Clone git repo ${{ vars.GIT_REPO_URL }}
        run: |
          url=${{ vars.GIT_REPO_URL }}
          git clone $url git_repo

      - name: Read git repo commits
        run: |
          python3 read_git_repo.py

      - name: Run dbt + PipeRider for main branch
        run: |
          dbt run
          piperider run --dbt-state target/

      - name: Run dbt + PipeRider for current pull request
        run: |
          git fetch
          git checkout $GITHUB_HEAD_REF
          dbt run
          piperider run --dbt-state target/

      - name: Generate Comparison reports + Summary
        run: |
          piperider compare-reports --last
          pushd .piperider/comparisons/latest
          zip -r comparison-report.zip ./
          popd
          cp .piperider/comparisons/latest/summary.md comparison-report-summary.md
          mv .piperider/comparisons/latest/comparison-report.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: comparison-report-artifact
          path: comparison-report.zip

      - name: Deploy to GitHub pages
        run: |
          mkdir -p comparisons/${{ github.run_id }}
          cp -r .piperider/comparisons/latest/* comparisons/${{ github.run_id }}/

          git checkout gh-pages
          if [[ $? != 0 ]]; then
            echo "gh-pages not found. create an empty gh-pages branch"
            git checkout --orphan gh-pages
          fi

          git config --local user.name 'github-actions'
          git add comparisons
          git commit -m "deploy to gh-pages"
          git push origin gh-pages -f
          echo "Deploy gh-pages completed"

      - name: Prepare Comparison Summary
        run: |
          echo "# :bar_chart: Piperider Comparison Summary" > summary.md
          cat comparison-report-summary.md >> summary.md
          echo -e "\n" >> summary.md
          echo "## :paperclip: Generated Comparison Report ZIP" >> summary.md
          echo "Find it in the [Github Action Runs Page](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> summary.md

      - name: Create PR Comment
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body-file: summary.md
