name: Run dbt + RipeRider

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up dbt + PipeRider
        run: |
          pip install -r requirements.txt

      - name: Clone git repo and fetch stats from github API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make fetch

      - name: Load to duckdb
        run: |
          make load

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Run dbt + PipeRider for main branch
        run: |
          dbt deps
          dbt run
          piperider run --dbt-state target/

      - name: Run dbt + PipeRider for current pull request
        run: |
          git fetch
          git checkout $GITHUB_HEAD_REF
          dbt deps
          dbt run
          piperider run --dbt-state target/

      - name: Generate Comparison reports + Summary
        run: |
          piperider compare-reports --last
          pushd .piperider/comparisons/latest
          zip -r comparison-report.zip ./
          popd
          cp .piperider/comparisons/latest/summary.md comparison-report-summary.md
          cp .piperider/comparisons/latest/comparison-report.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: comparison-report-artifact
          path: comparison-report.zip

      - name: Prepare Comparison Summary
        run: |
          echo "# :bar_chart: Piperider Comparison Summary" > summary.md
          cat comparison-report-summary.md >> summary.md
          echo -e "\n" >> summary.md
          echo "## :paperclip: Generated Comparison Report ZIP" >> summary.md
          echo "Find it in the [Github Action Runs Page](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> summary.md

      - name: Create PR Comment
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body-file: summary.md
