name: Run dbt + RipeRider

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up dbt + PipeRider
        run: |
          pip install -r requirements.txt

      - name: Clone git repo and fetch stats from github API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make fetch

      - name: Load to duckdb
        run: |
          make load

      - name: prepare target/manifest.json (workaround)
        run: |
          dbt deps
          dbt compile

      - name: PipeRider Compare
        uses: InfuseAI/piperider-compare-action@v1
