name: Run dbt + RipeRider

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up dbt + PipeRider
        run: |
          pip install -r requirements.txt
          pip install 'piperider[duckdb]'

      - name: Clone git repo ${{ vars.GIT_REPO_URL }}
        run: |
          url=${{ vars.GIT_REPO_URL }}
          git clone $url git_repo

      - name: Read git repo commits
        run: |
          python3 read_git_repo.py

      - name: Run dbt + PipeRider for main branch
        run: |
          dbt run
          piperider run

      - name: Run dbt + PipeRider for current pull request
        run: |
          git fetch
          git checkout $GITHUB_HEAD_REF
          dbt run
          piperider run

      - name: Generate Comparison reports + Summary
        run: |
          piperider compare-reports --last
          pushd .piperider/comparisons/latest
          zip -r comparison-report.zip ./
          popd
          cp .piperider/comparisons/latest/summary.md .
          cp .piperider/comparisons/latest/comparison-report.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: comparison-report-artifact
          path: comparison-report.zip

      - name: Create PR Comment
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body-file: summary.md
