name: Run dbt + RipeRider

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      git_repo_url:
        description: 'Git repo url to analyze'
        default: ${{ vars.GIT_REPO_URL }}
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo vars
        run: |
          echo "git url: ${{ vars.GIT_REPO_URL }}"
          echo "input: ${{ github.event.inputs.git_repo_url }}"

      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up DBT + PipeRider
        run: |
          pip install -r requirements.txt
          pip install 'piperider[duckdb]'

      - name: Clone git repo
        run: |
          git clone ${{ vars.GIT_REPO_URL }} git_repo

      - name: Read git repo commits
        run: |
          python3 read_git_repo.py

      - name: List dir
        run: |
          ls -al

      - name: Run dbt
        run: |
          dbt run
          dbt test

      - name: Run PipeRider
        run: |
          piperider run
